### ISSUE TITLE
Change the package name of Android library

### ISSUE THREAD

**Issue by neetrath** [rmcfarlane82/react-native-msal-plugin#10]
The package name of this plugin 'com.reactlibrary' that specify in AndroidManifest.xml is conflict with another plugin when I tried to export the release apk.

Please change the package name to other name. Maybe com.rmcfarlane should be ok.

**Comment by rmcfarlane82** [comment]
@neetrath Thank's, i'll update this for the next version.

**Comment by rmcfarlane82** [comment]
The package has been renamed in the latest version v3.0.0 #13
