### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'RNMsalPlugin.acquireTokenAsync'

### ISSUE THREAD

**Issue by oferns** [rmcfarlane82/react-native-msal-plugin#17]
Im trying to use the Common login in a project but am getting the following error

`{ [TypeError: undefined is not an object (evaluating 'RNMsalPlugin.acquireTokenAsync')]`

on line 22 of MsalPlugin.js

I feel like I am doing something obvious wrong. Any thoughts?

**Comment by rmcfarlane82** [comment]
Hi have you linked the library? react-native link react-native-msal-plugin

**Comment by rmcfarlane82** [comment]
also you have to do a pod install

**Comment by oferns** [comment]
Yeah I had. What I hadn't done was import it in MainApplication.java. Thanks for getting back to me though.

**Comment by rmcfarlane82** [comment]
glad you got it sorted, any issues let me know
