### ISSUE TITLE
Redirect URL and misleading error

### ISSUE THREAD

**Issue by oferns** [rmcfarlane82/react-native-msal-plugin#18]
Im now getting the following error

`[Error: Intent filter for: BrowserTabActivity is missing.  Please refer to the MSAL readme.]`

It seems to suggest this issue
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/479

Is there somewhere other than the AndroidManifest.xml file I need to add the app id to?

**Comment by oferns** [comment]
Indeed there was. In order to get this to work I had to change the authority to https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize

Thanks again for your efforts and time today,

**Comment by rmcfarlane82** [comment]
Thanks for the update, is there any documentation you think i need to add?

**Comment by oferns** [comment]
Im not sure really. The documentation at https://github.com/AzureAD/microsoft-authentication-library-for-android helped. Maybe add the bit about adding 

`import com.microsoft.identity.client.*;`
and 

```
 protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
...
          new RNMsalPluginPackage()
```

which were the cause of my null reference issue...Also the sample app you provided is very useful. Maybe highlight that it exists in the repo?

**Comment by rmcfarlane82** [comment]
Okay thanks for the input, i'm hoping to update the library soon so i'll add that to the readme when i do.

**Comment by VadimCeretean** [comment]
got the same error [Error: Intent filter for: BrowserTabActivity is missing. Please refer to the MSAL readme.]
I create few apps, one app is working but another show this error

**Comment by Hideiki** [comment]
+1

**Comment by rmiragaya** [comment]
+1

**Comment by defi-bear** [comment]
Maybe you add wrong scheme in android:scheme check the example
