### ISSUE TITLE
Cannot read property 'acquireTokenAsync' of undefined

### ISSUE THREAD

**Issue by danhnguyeen** [rmcfarlane82/react-native-msal-plugin#29]
Hi there,

I have an issue.
When I call `authClient.acquireTokenAsync()`, it shown the bellow error on iOS
```
TypeError: Cannot read property 'acquireTokenAsync' of undefined
    at MsalPlugin.acquireTokenAsync (MsalPlugin.js:22)
    at loginWithMicrosoft$ (Login.js:67)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:170
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
```

Could you tell me how to fix please?
Thanks in advance.
```
"react-native": "0.59.8",
"react-native-msal-plugin": "^3.0.0"
```
Platform: iOS

**Comment by danhnguyeen** [comment]
this bug was resolved by downgraded the msal version
`pod 'MSAL', '0.2.3'`
Thank you

**Comment by rmcfarlane82** [comment]
Hi, this project does need upgrading, it’s not tested on react-native 0.59 or the new MSAL library, also gradle needs to be updated, I’m not able to work on the project but hoping to get on top of things in August

**Comment by sm1th** [comment]
@rmcfarlane82 let me know if I can help get things rolling, I'd be happy to submit some PRs if I could.

**Comment by rmcfarlane82** [comment]
@sm1th I would be very happy for any help and improvements with the project, if you submit any pull requests i will do my best to get them reviewed, merged in and released.

**Comment by sm1th** [comment]
@rmcfarlane82 I've started work on upgrading the plugin to react native v0.60.x. Here is my branch: https://github.com/sm1th/react-native-msal-plugin/tree/feature/upgrade-to-rn-60. Once I get this working on iOS I will attempt to upgrade the MSAL pod dependency and fix breaking changes.

**Comment by WolfyUK** [comment]
@sm1th How far did you manage to get with the upgrade? Is your fork stable enough to prototype against?

**Comment by sm1th** [comment]
Hi @WolfyUK, it's been around a month since I've done work on it, but if my memory serves me right I think it is stable enough. I will double check later today though, I may have some unpushed code.

**Comment by sm1th** [comment]
Hi @WolfyUK, just wanted to notify you that I will not be continuing with the upgrade for this project. I do not have the time to do so, and I am now using [AppCenter Auth](https://docs.microsoft.com/en-us/appcenter/auth/) for authentication for our app, which is updated regularly and has support for iOS 13. If you check all the boxes for its requirements, I highly recommend using it. 

Cheers, and thanks @rmcfarlane82 for providing this plugin which helped us authenticate until we switched to AppCenter Auth a few days ago.

**Comment by WolfyUK** [comment]
Hi @sm1th, thanks for letting me know. I upgraded your fork before migrating to App Center myself a few weeks ago. I have had a few issues with Auth, but the MS support for that product seems pretty decent. This plugin definitely helped me out in the early days though, so thanks too @rmcfarlane82!

**Comment by rmcfarlane82** [comment]
@sm1th @WolfyUK I've not been able to get back onto this project, I think we will be using Azure B2C ROPC with a native login so no browser but AppCenter Auth is the way to go now.
