### ISSUE TITLE
Information: Microsoft cancelled App Center Auth

### ISSUE THREAD

**Issue by askpatrickw** [rmcfarlane82/react-native-msal-plugin#38]
"we are discontinuing efforts in the Auth, Data, and Push services and working to retire these preview services in App Center. "
https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/

**Comment by josmithua** [comment]
Dang

**Comment by josmithua** [comment]
Well we need B2C sign-in for our production app, and as far as I know @rmcfarlane82 doesn't have plans to work on this plugin, so my company has decided to put resources toward a new react native msal package, initially based off of this one to make development quicker. Will update here with repo details asap.

Please let me know if you wish to contribute and/or have any ideas re: a new plugin.

**Comment by rmcfarlane82** [comment]
Ooo that’s a bit rubbish, I’ll try to upgrade to the latest rn over the weekend, least the package will be up to date 👌

**Comment by WolfyUK** [comment]
@josmithua Yes, we will now be after a similar solution. I had forked this repo privately for a few fixes before switching to App Center Auth. Happy to contribute to a new solution, especially if this extends out to supporting a native sign in experience at some point (https://docs.microsoft.com/en-gb/azure/active-directory-b2c/configure-ropc).

**Comment by askpatrickw** [comment]
Its interesting to note that the Microsoft AD library for JS can't be used with React Native because of its storage dependencies.  

Link to more information:  [microsoft-authentication-library-for-js will not work with React Native due to the inability to use LocalStorage or SessionStorage](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/825#issuecomment-511463881)

**Comment by WolfyUK** [comment]
@askpatrickw I noticed you have forked [GSingh01/ad-b2c-react-native](https://github.com/GSingh01/ad-b2c-react-native). Have you had a chance to evaluate this package? Our app is using the bare Expo workflow so this may be of use.

**Comment by josmithua** [comment]
I've been working on this for the past couple days and currently have B2C interactive login working for iOS. Not ready to publish code just yet but will do as soon as possible. 

@WolfyUK thanks for your support!

**Comment by askpatrickw** [comment]
@WolfyUK  No, Sorry. I've not actually dug into that yet. I'm working on a non react native project this week.

**Comment by josmithua** [comment]
Done iOS and almost finished Android...

**Comment by WolfyUK** [comment]
@josmithua Great to hear! 

For information, the Auth SDK removals from App Center happened in [this PR for Android](https://github.com/microsoft/appcenter-sdk-android/pull/1362) and [this one for iOS](https://github.com/microsoft/appcenter-sdk-apple/pull/1961). I'm wondering what the benefits may be of forking those repos to keep AppCenter Auth alive in some format versus moving back to a library such as this.

**Comment by josmithua** [comment]
Alrighty folks, I'd like to introduce you to react-native-msal, the up-to-date React Native MSAL module brought to you by [Stash Energy](https://stash.energy)

github: https://github.com/stashenergy/react-native-msal
npmjs: https://www.npmjs.com/package/react-native-msal

Honestly this is my/our first published library, so you can expect some doozies along the way, but I hope that it can provide for the needs of your React Native application.

If you have any issues, feature requests, suggestions, etc., please feel free to create an issue in the repo. I look forward to your feedback and pull requests 😄.

(As of this comment, the Azure pipeline/Github action is failing due to an issue with npm/caching, but you should see a green check soon.)

Cheers, 
Joshua

**Comment by rmcfarlane82** [comment]
@josmithua awesome, I’ve updated docs to use this 👍
