### ISSUE TITLE
Methods acquireTokenSilentAsync and tokenCacheB2CDeleteItem fails with "Invalid B2C authority" error

### ISSUE THREAD

**Issue by daymansiege** [rmcfarlane82/react-native-msal-plugin#4]
When using standard authority string (e.g. https://login.microsoftonline.com/tfp/{COMPANY}.onmicrosoft.com or https://{COMPANY}.b2clogin.com/tfp/{COMPANY}.onmicrosoft.com) works fine for aquireTokenB2CAsync however it fails for methods acquireTokenSilentAsync and tokenCacheB2CDeleteItem with error "Invalid B2C authority".
It lloks like internal Java error in com.microsoft.identity.client.B2cAuthority.updateAuthority() where number of URI segments are expected to be equal to com.microsoft.identity.client.B2cAuthority.B2C_AUTHORITY_SEGMENTS_SIZE = 3. (https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/v0.1.3/msal/src/authority/java/com/microsoft/identity/client/B2cAuthority.java)
But if I pass authority + "/policy" (e.g. https://login.microsoftonline.com/tfp/{COMPANY}.onmicrosoft.com/b2c_1_susi) they both work fine.
Is it the initial purpose of having authority parameter in these methods?
And if I replace authority in the constructor with "augmented" one, then resetPasswordAsync behaves incorrectly and redirects to login.
Why can't all methods use authority that was passed into constructor + add IPolicies to the constructor, so each method will just grab a policy for itself and build a proper authority URI for com.microsoft.identity.client.B2cAuthority?

**Comment by rmcfarlane82** [comment]
This relates to issue #1 , at the moment you have to pass the authority into these methods, i'm looking to change this behavior in the next week or so, need to update the package to use the latest version of msal (issue #3)  which has breaking changes in it so i'm looking to address all of these issues and probably release a version 2.0.

the authority used is returned in the Authentication Result so you can store and pass that into the refresh methods for now.

**Comment by daymansiege** [comment]
Thank you!
Looking forward for updates!

**Comment by sm1th** [comment]
@rmcfarlane82 Any updates on the updates? 😄 Hoping to use this plugin to make a ReactXP extension

**Comment by rmcfarlane82** [comment]
I’m looking to do a release at the end of this week, there are breaking changes, I’ll list them all out in the readme, the v2 branch isn’t quite there yet but I’m hoping Friday 23

**Comment by sm1th** [comment]
Great, thanks!

**Comment by rmcfarlane82** [comment]
ready for build #5

**Comment by rmcfarlane82** [comment]
#5 ready for a build

**Comment by sm1th** [comment]
@rmcfarlane82 Are you publishing to npm soon?

**Comment by rmcfarlane82** [comment]
@sm1th there is a beta version on npm, if you find any issues let me know.

**Comment by rmcfarlane82** [comment]
this shouldn't be an issue in release 2.0.0 so i'm going to close this one
