### ISSUE TITLE
gradlew assembleRelease problem

### ISSUE THREAD

**Issue by neetrath** [rmcfarlane82/react-native-msal-plugin#7]
I use this library in debug mode. it's good.

But when I tried to export release apk file. 
I always got the 'Task :app:transformDexArchiveWithDexMergerForRelease FAILED' error.

After I remove  implementation project(':react-native-msal-plugin') . The error disappear.

I tried to add  implementation project(':react-native-msal-plugin') again. The error comeback.

Is anyone face this problem?

**Comment by rmcfarlane82** [comment]
I've not seen this issue, i can't reproduce, what gradle version are you on?

have you tried removing both 'build' folder in /android and /android/app
and build again?

**Comment by neetrath** [comment]
Can be resolved by #10
